### ISSUE TITLE
Errors in Habr article about downloading music from VK

### ISSUE THREAD

**Issue by eugeneandrienko** [tachycardiazxc/ApiTest#1]
Hello. Is this your article in Habr: [Как получать музыку из ВКонтакте в 2022 году](https://habr.com/ru/post/677258/)? I didn't found any another option to write a message to you, so I write a new issue here :-).

Помимо ряда опечаток в коде в начале статьи, вроде замены `_` на `.` в имени переменной:
```
m3u8_data = m3u8.load(url="")
segments = m3u8.data.get("segments")
```

В коде есть одна большая проблема, которая не позволяет склеить ts-файл корректно. Если ts-файлов от VK много, то в массиве `segments_file` в методе `_compile_audio` они расположены вперемешку:
```
(ins)>>> for file in segments_file:
(ins)...     print(file)
(ins)...
seg-96-a1.ts
seg-75-a1.ts
seg-105-a1.ts
seg-83-a1.ts
seg-24-a1.ts
seg-127-a1.ts
seg-50-a1.ts
seg-151-a1.ts
seg-142-a1.ts
```

И в итоге при склеивании получается мешанина в итоговом mp3.

На скорую руку я нашёл следующее решение:
1) В bash, в каталоге со скачанными сегментами переименовываем скачанные сегменты - добавляем нули к номеру сегмента, чтобы он был отсортрован корректно.
`for i in *; do NUM=$(echo $i | sed -r 's/seg-([0-9]+)-a1.ts/\1/g'); PADDED_NUM=$(printf '%05d' "$NUM"); mv -v "$i" "seg-$PADDED_NUM-a1.ts"; done`
2) В Python сортируем массив segments_file перед использованием:
`segments_file.sort()`

Ещё одна замеченная проблема - часть кода:
```
segments_path = "segments/"
segments_file = os.listdir(segments_path)
for file in segments_file:
    f = open(f"../m3u8_downloader/{segments_path}/{file}", "rb").read()
    open("../m3u8_downloader/mp3/temp.ts", "ab").write(f)
```

Не работает потому что не находит каталог segments/ в текущем каталоге. Заработал следующий код:
```
segments_path = "../m3u8_downloader/segments/"
segments_file = os.listdir(segments_path)
for file in segments_file:
    f = open(f"{segments_path}/{file}", "rb").read()
    open("../m3u8_downloader/mp3/temp.ts", "ab").write(f)
```

**Comment by tachycardiazxc** [comment]
Здравствуйте, спасибо большое за оставленный комментарий на счет моей статьи. Большинство проблем из статьи были решены в моем текущем проекте, который изначально упоминался в статье, а именно дискорд боте.
Вы так же можете просмотреть этот проект, если вам интересно!
Я так же чуть позже приступлю к исправлению всех ошибок в своей статье на хабре, еще раз большое спасибо за ваш комментарий!

проект: [https://github.com/tachycardiazxc/DiscordBot/blob/master/src/music_downloader/downloader.py](DiscrodMusicBot)
